"""add_users

Revision ID: 48c414be4328
Revises: 25245ea135ca
Create Date: 2026-02-08 19:32:43.232711

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "48c414be4328"
down_revision: Union[str, Sequence[str], None] = "25245ea135ca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("uuid", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="orders",
    )
    op.create_index(op.f("ix_orders_users_email"), "users", ["email"], unique=True, schema="orders")
    op.create_index(op.f("ix_orders_users_uuid"), "users", ["uuid"], unique=True, schema="orders")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_orders_users_uuid"), table_name="users", schema="orders")
    op.drop_index(op.f("ix_orders_users_email"), table_name="users", schema="orders")
    op.drop_table("users", schema="orders")
    # ### end Alembic commands ###
